table(collision$`NUMBER OF MOTORIST INJURED`)
hist(collision$`NUMBER OF PEDESTRIANS INJURED`, main = "Histogram of Number of Pedestrians Injured in Car Accidents in New York City", xlab = "Number of Pedestrians Injured")
table(collision$`NUMBER OF PEDESTRIANS INJURED`)
range(collision$`NUMBER OF PEDESTRIANS INJURED`)
table(collision$BOROUGH)
barplot(table(collision$BOROUGH), main = "Number of Car Accidents for each Burough", xlab = "Burough", ylab = "Frequency")
hist(collision$`NUMBER OF MOTORIST INJURED`, main = "Histogram of Number of Motorists Injured in Car Accidents in New York City", xlab = "Number of Motorists Injured")
range(collision$`NUMBER OF MOTORIST INJURED`)
barplot(table(collision$`VEHICLE TYPE CODE 1`), main = "Vehicle Type for Car Accidents in New York City", xlab = "Vehicle Type", ylab = "Frequency")
table(collision$`VEHICLE TYPE CODE 1`)
max(collision$`NUMBER OF PEDESTRIANS INJURED`)
median(collision$`NUMBER OF PEDESTRIANS INJURED`)
mean(collision$`NUMBER OF PEDESTRIANS INJURED`)
max(collision$`NUMBER OF PEDESTRIANS INJURED`)
range(collision$`NUMBER OF PEDESTRIANS INJURED`)mean(collision$`NUMBER OF PEDESTRIANS INJURED`, trim = 0.05)
mean(collision$`NUMBER OF MOTORIST INJURED`, trim = 0.05)

median(collision$`NUMBER OF PEDESTRIANS INJURED`)

